name: Array
main: com.fadelands.array.Array
version: ARRAY-1.0
author: arrayofc

commands:
  uptime:
    description: Receive sub-server up time.
  dbstatus:
    description: Receive information about the Array database.
  whois:
    aliases: [userinfo]
    description: Receive information about a player.
  punish:
    aliases: [p]
    description: Punish a user.
  ban:
    description: Ban a user.
  mute:
    description: Mute a user.
  unban:
    description: UnBan a user.
  unmute:
    description: UnMute a user.
  history:
    description: Check a players punishment history.
  alts:
    description: Check a users alt accounts.