name: Array
main: com.fadelands.array.Array
version: ARRAY-1.0
author: arrayofc

commands:
  uptime:
    description: Receive sub-server up time.
  dbstatus:
    description: Receive information about the Array database.
  punish:
    aliases: [p]
    description: Punish a user.
  ban:
    description: Ban a user.
  mute:
    description: Mute a user.
  unban:
    description: UnBan a user.
  unmute:
    description: UnMute a user.
  history:
    description: Check a player punishment history.
  alts:
    description: Check a users alt accounts.
  lockdown:
    description: Lock the network for public player.
  staffsettings:
    description: Change staff settings
  staff:
    description: Admin command
  vanish:
    description: Toggle staff mode
    aliases: [modmode]
  profile:
    description: View your user profile
  achievement:
    aliases: [achievements, ach]
    description: Check your achievements.
  help:
    description: Used if you need help.
  guides:
    description: Browse our guides.
  color:
    aliases: [namecolor]
    description: Select a name color.
  list:
    aliases: [playersonline, playerlist]
    description: Show who is online.
  settings:
    description: Change your settings.
  chatslow:
    description: Slow down the chat.
  silencechat:
    description: Silence the chat.