name: Lobby
version: 1.0
author: arrayofc
main: com.fadelands.lobby.Main
depend: [Core]

commands:
  createnpc:
  buildmode:
    description: Toggle between build mode.
    aliases: [bm]
  lobbysettings:
    description: Change your lobby settings.
    aliases: [ls, lsettings]
  setlobby:
    description: Set lobby spawn location