name: SkyBlockAir
main: com.fadelands.sbair.Main
version: 1.0
author: arrayofc
depend: [Core, Core, SignGUI, ASkyBlock]

commands:
  islandmenu:
    aliases: [ismenu, issettings, ishelp, menu]
    description: Open the island menu.
  warp:
    aliases: [warps]
    description: Opens the warp menu.