#########################
### DATABASE SETTINGS ###
#########################

host: 'localhost'
port: '3306'
database: 'server'
username: 'root'
password: ''

#########################
### TABLIST OPTIONS###
#########################

header-text: Test

footer-text: Test