name: Core
main: com.fadelands.core.CorePlugin
version: 1.0
author: arrayofc
depend: [Array]

commands:
  profile:
    description: View your user profile
  saveplayerdata:
    description: Admin command
  achievement:
    aliases: [achievements, ach]
    description: Check your achievements.
  createnpc:
    description: Create a NPC.
  country:
    description: Lookup a players country.
  help:
    description: Used if you need help.
  color:
    aliases: [namecolor]
    description: Select a name color.
  list:
    aliases: [playersonline, playerlist]
    description: Show who is online.
  teleport:
    aliases: [tp, tpo]
    description: Tp to a user
  gamemode:
    aliases: [gm]
    description: Admin command
  sudo:
    description: Admin command
  fly:
    aliases: [flight]